config/routes.rb
Roadnottaken::Application.routes.draw do
  
  get "/legs/waypoint_up", to: "legs#waypoint_up"
  get "/legs/waypoint_down", to: "legs#waypoint_down"  
  
  resources :legs

  resources :trips

  resources :locations
  
  resources :waypoints

  root "pages#home"
  
  get "/home", to: "pages#home", as: "home"
  
  get "/signin", to: "sessions#new", as: "signin"
  post "/signin", to: "sessions#create"
  get "/signout", to: "sessions#destroy", as: "signout"
  
  namespace :admin do
    root "base#index"
    resources :users
  end
    
end

app/models/leg.rb
class Leg < ActiveRecord::Base

  belongs_to :trip
  
  #has_and_belongs_to_many :locations, -> { order "sort_flag ASC" }
  has_many :waypoints, :dependent => :destroy
  has_many :locations, -> { order "sort_flag ASC" }, :through => :waypoints
  
  accepts_nested_attributes_for :locations

end

app/controllers/legs_controller.rb
class LegsController < ApplicationController
  before_action :set_leg, only: [:show, :edit, :update, :destroy]

  def waypoint_up
    if params[:waypoint]
      if waypoint = Waypoint.find(params[:waypoint])
        waypoint.sort_flag += 1
        waypoint.save!
      end
    end
  end
  
  def waypoint_down
    if params[:waypoint]
      if waypoint = Waypoint.find(params[:waypoint])
        waypoint.sort_flag -= 1
        waypoint.save!
      end
    end
  end

  # GET /legs
  # GET /legs.json
  def index
    @legs = Leg.all
  end

  # GET /legs/1
  # GET /legs/1.json
  def show
    @location = Location.new
    if @leg.locations 
      @leg_hash = Gmaps4rails.build_markers(@leg.locations) do |location, marker|
        marker.lat location.latitude
        marker.lng location.longitude
        marker.title location.address
      end    
    else
      @leg_hash = nil
    end
     
  end

  # GET /legs/new
  def new
    @leg = Leg.new
  end

  # GET /legs/1/edit
  def edit
  end

  # POST /legs
  # POST /legs.json
  def create
  
    @leg = Leg.new(leg_params)

    respond_to do |format|
      if @leg.save
        format.html { redirect_to @leg, notice: 'Leg was successfully created.' }
        format.json { render :show, status: :created, location: @leg }
      else
        format.html { render :new }
        format.json { render json: @leg.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /legs/1
  # PATCH/PUT /legs/1.json
  def update
    respond_to do |format|
      if @leg.update(leg_params)
        format.html { redirect_to @leg, notice: 'Leg was successfully updated.' }
        format.json { render :show, status: :ok, location: @leg }
      else
        format.html { render :edit }
        format.json { render json: @leg.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /legs/1
  # DELETE /legs/1.json
  def destroy
    @leg.destroy
    respond_to do |format|
      format.html { redirect_to legs_url, notice: 'Leg was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_leg
      @leg = Leg.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def leg_params
      params.require(:leg).permit(:title, :description, :trip_id)
    end
end

app/helpers/legs_helper.rb
module LegsHelper
end

app/views/legs/_form.html.erb
<%= form_for(@leg) do |f| %>

  <% if @trip %>
    <%= f.hidden_field :trip_id, :value => @trip.id %>
  <% end %>

  <% if @leg.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@leg.errors.count, "error") %> prohibited this leg from being saved:</h2>

      <ul>
      <% @leg.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/legs/_list.html.erb
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @legs.each do |leg| %>
      <tr>
        <td><%= leg.title %></td>
        <td><%= leg.description %></td>
        <td><%= link_to 'Show', leg %></td>
        <td><%= link_to 'Edit', edit_leg_path(leg) %></td>
        <td><%= link_to 'Destroy', leg, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/legs/edit.html.erb
<h1>Editing leg</h1>

<%= render 'form' %>

<%= link_to 'Show', @leg %> |
<%= link_to 'Back', legs_path %>

app/views/legs/index.html.erb
<h1>Listing legs</h1>

<%= render :partial => 'list' %>

<br>

<%= link_to 'New Leg', new_leg_path %>

app/views/legs/new.html.erb
<h1>New leg</h1>

<%= render 'form' %>

<%= link_to 'Back', legs_path %>

app/views/legs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @leg.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @leg.description %>
</p>

<h2>Locations in this Leg</h2>
<% if @locations = @leg.locations %>
  
  <% @start = @locations.first %>
  <% @end = @locations.last %>
  
  <table>
    <thead>
      <tr>
        <th>Order</th>
        <th>Address</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @leg.waypoints.each do |waypoint| %>
        <tr>
          <td>
            <%= link_to 'Up', :action => 'waypoint_up', :waypoint => waypoint.id %> | 
            <%= link_to 'Down', :action => 'waypoint_down', :waypoint => waypoint.id %>
          </td>
          <td><%= waypoint.location.address %></td>
          <td><%= link_to 'Show', waypoint.location %></td>
          <td><%= link_to 'Edit', edit_location_path(waypoint.location) %></td>
          <td><%= link_to 'Destroy', waypoint.location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div style='width: 800px;'>
    <div id="map" style='width: 800px; height: 400px;'></div>
  </div>

  <script type="text/javascript">
    var directionsDisplay;
    var directionsService = new google.maps.DirectionsService();
    var map;
    var markerArray = [];
    var waypts = [];

    function initialize() {
      directionsDisplay = new google.maps.DirectionsRenderer();
      var start_point = new google.maps.LatLng(<%= @start.latitude if @start %>, <%= @start.longitude if @start %>);
      var mapOptions = {
        zoom:7,
        center: start_point
      };
      map = new google.maps.Map(document.getElementById('map'), mapOptions);
      directionsDisplay.setMap(map);
    }

    function calcRoute() {
      initialize();
      
      <% @count = 0 %>
      
      // Add waypoints 
      <% @locations.each do |location| %>
        <% if location != @start && location != @end %>
          waypts.push({
            location: new google.maps.LatLng(<%= location.latitude %>, <%= location.longitude %>),
            stopover: true
          });      
        <% end %>
      <% end %>
      
      var start = new google.maps.LatLng(<%= @start.latitude if @start %>, <%= @start.longitude if @start %>);
      var end = new google.maps.LatLng(<%= @end.latitude if @end %>, <%= @end.longitude if @end %>);
      
      var request = {
          origin:start,
          destination:end,
          optimizeWaypoints: true,
          travelMode: google.maps.TravelMode.DRIVING,
          waypoints: waypts
      };
      
      directionsService.route(request, function(response, status) {
        if (status == google.maps.DirectionsStatus.OK) {
          directionsDisplay.setDirections(response);
          var route = response.routes[0];
          var summaryPanel = document.getElementById('directions_panel');
          summaryPanel.innerHTML = '';
          // For each route, display summary information.
          for (var i = 0; i < route.legs.length; i++) {
            var routeSegment = i + 1;
            summaryPanel.innerHTML += '<b>Route Segment: ' + routeSegment + '</b><br>';
            summaryPanel.innerHTML += route.legs[i].start_address + ' to ';
            summaryPanel.innerHTML += route.legs[i].end_address + '<br>';
            summaryPanel.innerHTML += route.legs[i].distance.text + '<br><br>';
          }
        }
      });
    }

    google.maps.event.addDomListener(window, 'load', calcRoute);
  </script>
<% end %>

<div id="directions_panel" style="margin:20px;background-color:#FFEE77;"></div>

<h2>Create and Add a New Location</h2>
<%= render 'locations/form' %>

<%= link_to 'Edit', edit_leg_path(@leg) %> |
<%= link_to 'Back', legs_path %>